 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Install Dependencies
          command: npm run dev:react
      - run:
          name: seeding data
          command: npm run seed
      - run:
          name: Run Tests
          command: npm test
