 version: 2
 jobs:
   build:
    docker:
      - image: circleci/node:8.16

    working_directory: ~/repo
    
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: run npm
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run:
      #     name: Install Dependencies
      #     command: npm run dev:react
      - run:
          name: seeding data
          command: npm run seed
      - run:
          name: Run Tests
          command: npm test
